strlen($str);
strtoupper($str);
strtolower($str);
ucfirst($str);
lcfirst($str);
ucwords($str);
strpos($str, $search);
strrpos($str, $search);
str_replace($search, $replace, $str);
str_ireplace($search, $replace, $str);
explode($sep, $str);
implode($glue, $arr);
trim($str);
ltrim($str);
rtrim($str);
substr($str, $start, $length);
str_repeat($str, $times);
str_split($str, $length);
strcmp($str1, $str2);
strcasecmp($str1, $str2);
